### ISSUE TITLE
ExtensionOfTextView.onEditorAction clashes with TextView.onEditorAction

### ISSUE THREAD

**Issue by taig** [pfn/android-conversions#2]

**Comment by pfn** [comment]
Hmm, this is an interesting problem that I don't know how to solve at the moment. For now, you can workaround this by doing:

```
import com.hanhuy.android.conversions._
textfield.setOnEditorActionListener((v: View, i: Int, e: android.view.KeyEvent) => true)
```

**Comment by pfn** [comment]
In 1.3, you can do: `textfield.asScala.onEditorAction((a,b,c) => true)` (and for any other place where this naming collision occurs).
