### ISSUE TITLE
support-v4 conversions and extensions are empty

### ISSUE THREAD

**Issue by taig** [pfn/android-conversions#3]
Maybe it's just IntelliJ fooling me, but also when I clone and compile the repo, the generated v4 package objects are empty.

**Comment by pfn** [comment]
Yeah, result of the missing classes debacle. I'll publish a new version shortly. Thanks.

**Comment by pfn** [comment]
1.4

**Comment by taig** [comment]
Did you publish 1.4 to sonatype? I can't find or resolve it.

https://oss.sonatype.org/#nexus-search;quick~scala-conversion

**Comment by pfn** [comment]
Sorry, I forgot to release it from sonatype staging. It should be available
shortly.
